### ISSUE TITLE
Parsers for OpenEdition and CAIRN

### ISSUE THREAD

**Issue by ericjeangirard** [ourresearch/parseland#1]
Hello

OpenEdition (doi prefix 10.4000) and CAIRN (doi prefix 10.3917) are two major dissemination platforms in HSS in French language.
Getting their author and affiliation metadata would help increase OpenAlex metadata quality in this area.

Similar parsers are implemented there https://github.com/dataesr/bso-parser-html/blob/main/project/server/main/parsers/cairn.py and https://github.com/dataesr/bso-parser-html/blob/main/project/server/main/parsers/openedition.py

**Comment by nolanm1122** [comment]
Hi Eric, these 2 parsers were implemented in these commits:

https://github.com/ourresearch/parseland/commit/d9ff646b7c6b112f7f2a7f45ede52a0d3d0cfa4b
https://github.com/ourresearch/parseland/commit/b144e3e90b7686cc7120aa0e6dc5a60c6d4d3fbc

Closing this issue.

**Comment by ericjeangirard** [comment]
Awesome! Thanks @nolanm1122

**Comment by ericjeangirard** [comment]
Hi !
I noticed a problem on the OpenEdition parser (for affiliation)
For example
Hi
In https://api.openalex.org/works?filter=doi:10.4000/rdr.1353
the raw affiliation indicated is “Laïcité et République. Considérations sur la République française, Paris” 
In the HTML https://doi.org/10.4000/rdr.1353 that corresponds the the references section.

The raw affiliation should be “Maître de conférences en droit public, Université de Perpignan Via Domitia, Centre du droit économique et du développement (CDED)”
