### ISSUE TITLE
Getting more metadata (references in particular) from the parsing ?

### ISSUE THREAD

**Issue by ericjeangirard** [ourresearch/parseland#2]
Hello
It seems that much more metadata than only authors and affiliations could be retrieved through parsing (html or pdf via grobid).
Would you consider getting references (which would improve A LOT number of citations in OpenAlex), and abstracts for example ?

**Comment by ericjeangirard** [comment]
Hi @nolanm1122 and @jasonpriem 
I comment here to be a bit more specific, even though that should be an issue for the https://github.com/ourresearch/openalex-pdf-parser repo (but issues are not allowed there).
For now `authors`, `affiliations` and `references` are extracted from grobid, which is already great.
It may not cost a lot to add extra metadata detected by grobid, especially `fundings` (see https://github.com/dataesr/bso3-analyse-publications/blob/main/application/server/main/parse_grobid.py#L89 for an implementation of this parsing).
Also `keywords` and the new `has_availability_statement` can be very interesting for a lot of folks.
`acknowledgments` are there as well.

**Comment by nolanm1122** [comment]
Hi @ericjeangirard.

I'm not sure about `keywords` specifically, but I do know we already collect acknowledgments, funding, and others via [this code snippet](https://github.com/ourresearch/openalex-pdf-parser/blob/master/parse/grobid.py#L177-L181) in openalex-pdf-parser. Thanks though!
